apiVersion: apps/v1
kind: Deployment
metadata:
  name: sls-master-deploy
  labels:
    app: sls_master_deploy
    version: 1.0.2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sls_master_pod
  template:
    metadata:
      labels:
        app: sls_master_pod
        version: 1.0.2
    spec:
      containers:
      - name: master
        image: 125111317/simple_load_simulator:master-1.0.2
        resources:
          limits:

            cpu: "500m"
        env:
            - name: PYTHONUNBUFFERED
              value: "1"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 7790
        ports:
         - containerPort: 7790
---
apiVersion: v1
kind: Service
metadata:
  name: sls-master-service
spec:
  selector:
    app: sls_master_pod
  ports:
    - name: http-master
      protocol: TCP
      port: 7790
      targetPort: 7790
