apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels: 
    app: tester-inside
    version: 1.0.1
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    env:
    - name: MY_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: MY_POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "apt update && apt install vim curl -y ;  sleep 3600;" ]
#kubectl exec -it ubuntu -- /bin/bash
